server:
  port: 2300

spring:
  application:
    name: spring-cloud-eureka-client-consumer-ribbon
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 2000MB      # Max file size，默认1M
      max-request-size: 2500MB   # Max request size，默认10M
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true   # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/