server:
  port: 4100

spring:
  application:
    name: sping-cloud-eureka-config
  profiles:
    #使用本地属性文件
    active: native
  cloud:
    config:
      server:
        native:
          #属性文件地址，只要指定文件夹的路径
          search-locations: classpath:/properties/
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/