server:
  port: 2100

spring:
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 2000MB      # Max file size，默认1M
      max-request-size: 2500MB   # Max request size，默认10M
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  application:
    name: sping-cloud-eureka-server-upload

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}  # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为IP地址
    lease-renewal-interval-in-seconds: 5 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 15 # 如果现在超过了5秒的间隔（默认是90秒）
  client: # 客户端进行Eureka注册的配置
    healthcheck:
      enabled: true   # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 解决Feign/Ribbon第一次请求失败的问题
            timeoutInMilliseconds: 6000

info:
  app.name: sping-cloud-eureka-server-upload
  company.name: com.alen
  build.artifactId: $project.artifactId$
  build.version: $project.verson$